export const portfolioConfig = {
  name: "riycreatess",
  title: "Creative Developer & Designer",
  tagline: ["Developer", "Designer", "Creator"],
  avatar: "/assets/mascot.png",
  bio: [
    "I'm a creative developer who loves building beautiful, functional interfaces. With years of experience across the full stack, I turn complex problems into elegant digital experiences.",
    "My approach blends design thinking with clean engineering. Every pixel matters, every line of code serves a purpose.",
    "When I'm not coding, you'll find me exploring new tools, contributing to open source, or sketching UI concepts.",
  ],
  nav: ["Home", "About", "Projects", "Blog", "Contact"],
  skills: [
    { category: "Frontend", techs: ["React", "TypeScript", "Tailwind CSS", "Next.js", "Framer Motion"] },
    { category: "Backend", techs: ["Node.js", "Python", "PostgreSQL", "GraphQL", "REST APIs"] },
    { category: "Tools & Design", techs: ["Figma", "Git", "Docker", "VS Code", "Vercel"] },
  ],
  experience: [
    {
      year: "2025",
      title: "Senior Developer",
      company: "Creative Agency",
      period: "Jan 2024 – Present",
      description: "Leading frontend architecture and building scalable design systems for enterprise clients. Mentoring junior developers and driving technical decisions.",
    },
    {
      year: "2023",
      title: "Full Stack Developer",
      company: "Tech Startup",
      period: "Jun 2022 – Dec 2023",
      description: "Built and shipped multiple products from concept to production. Worked across the entire stack with React, Node.js, and cloud infrastructure.",
    },
    {
      year: "2021",
      title: "Junior Developer",
      company: "Digital Studio",
      period: "Mar 2021 – May 2022",
      description: "Developed responsive web applications and contributed to internal tooling. Gained deep experience with modern frontend frameworks.",
    },
  ],
  projects: [
    {
      title: "Project Aurora",
      description: "A design system component library with accessibility-first principles and dark mode support.",
      image: "/assets/projects/p1.png",
      techs: ["React", "TypeScript", "Storybook"],
      liveUrl: "https://example.com",
      githubUrl: "https://github.com",
    },
    {
      title: "WeatherViz",
      description: "Real-time weather visualization dashboard with interactive maps and historical data charts.",
      image: "/assets/projects/p2.png",
      techs: ["Next.js", "D3.js", "OpenWeather API"],
      liveUrl: "https://example.com",
      githubUrl: "https://github.com",
    },
    {
      title: "TaskFlow",
      description: "Kanban-style project management tool with drag-and-drop, real-time collaboration, and team workspaces.",
      image: "/assets/projects/p3.png",
      techs: ["React", "Node.js", "Socket.io"],
      liveUrl: "https://example.com",
      githubUrl: "https://github.com",
    },
    {
      title: "PixelPlay",
      description: "Retro pixel-art game engine built with Canvas API featuring sprite editor and level designer.",
      image: "/assets/projects/p4.png",
      techs: ["TypeScript", "Canvas API", "Web Workers"],
      liveUrl: "https://example.com",
      githubUrl: "https://github.com",
    },
  ],
  blog: [
    {
      title: "Building Accessible Design Systems",
      date: "2025-01-15",
      readingTime: "6 min",
      excerpt: "Lessons learned from building a component library that works for everyone, from screen readers to keyboard navigation.",
      url: "https://example.com",
    },
    {
      title: "The Art of Performance Optimization",
      date: "2024-11-20",
      readingTime: "8 min",
      excerpt: "Deep dive into Core Web Vitals, lazy loading strategies, and how we cut our Largest Contentful Paint by 60%.",
      url: "https://example.com",
    },
    {
      title: "Why I Switched to TypeScript",
      date: "2024-09-05",
      readingTime: "5 min",
      excerpt: "A practical look at how TypeScript improved our code quality, developer experience, and team velocity.",
      url: "https://example.com",
    },
  ],
  contact: {
    email: "hello@riycreatess.dev",
    formspreeId: "YOUR_ID",
  },
  socials: {
    github: "https://github.com/riycreatess",
    twitter: "https://twitter.com/riycreatess",
    linkedin: "https://linkedin.com/in/riycreatess",
    instagram: "https://instagram.com/riycreatess",
  },
  accentColor: "#7c3aed",
};
